### ISSUE TITLE
where is you "setup.py" for CUDA extension? 

### ISSUE THREAD

**Issue by semchan** [ashawkey/torch-ngp#1]
thanks for your great work. but may I know how to run your code? thanks a lot.

**Comment by ashawkey** [comment]
We use [load](https://pytorch.org/docs/stable/cpp_extension.html#torch.utils.cpp_extension.load) to build the extension just-in-time. You can directly run the python code, and the CUDA extension will be built automatically.

**Comment by semchan** [comment]
> We use [load](https://pytorch.org/docs/stable/cpp_extension.html#torch.utils.cpp_extension.load) to build the extension just-in-time. You can directly run the python code, and the CUDA extension will be built automatically.

thanks very much for your reply. But when I run “bash scripts/run_nerf.sh”， I meet "
RuntimeError: Ninja is required to load C++ extensions". Can you help me? thanks

**Comment by semchan** [comment]
I fixed this by " apt install ninja", but I got the following error:

Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

**Comment by ashawkey** [comment]
As the error says, you may set g++ as the compiler. Maybe [this issue](https://github.com/NVIDIA/apex/issues/974) could help?

**Comment by semchan** [comment]
thanks very much. after fixed this issue, it still pop the error: No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-10.2'.  I have check that the runing cuda version is the same as the version matched in pytorch.

**Comment by ashawkey** [comment]
Maybe refer to [this issue](https://github.com/open-mmlab/mmdetection/issues/281#issuecomment-668486013)?

**Comment by ashawkey** [comment]
closed for now.
