### ISSUE TITLE
Larger num_levels is not supported

### ISSUE THREAD

**Issue by wangjksjtu** [ashawkey/torch-ngp#10]
Hi @ashawkey , Thanks for the awesome work!

It seems I cannot use larger `num_levels` (e.g., `num_levels = 32`). There are some inf/-inf after the hash encoding. Do you have any ideas (might be relevant to fast hash cuda operation)?

Also, do you have any plans to implement the `aabb_scale` occupancy grid (to model larger unbounded scene, e.g., fox) as the original instant-ngp implementation?

**Comment by ashawkey** [comment]
Hi,
Can you run the newest example code on the fox dataset? The default `num_levels` is `16` and it should be able to work.
As for the `aabb_scale`, you could enlarge the `--bound` parameter to achieve a similar effect (the scene is assumed to be bounded in `Box[-bound, bound]`, so a larger bound allows the ray to travel further. For the fox dataset, the default `bound=2` should work fine).

**Comment by wangjksjtu** [comment]
Thanks for the prompt reply! Sorry, there is a typo in the last message (`num_levels=16` -> `num_levels=32`). I tried to enlarge it to 32, but got the `-inf/inf` issue. 

For the bound, thanks and I will try that! it seems that the current implementation is doing uniform sampling in Box[-bound, bound]? However, in the original instant-ngp, they are doing uniform in unit cube, and exponential sampling in outside range?

**Comment by ashawkey** [comment]
1. I tried 32 in the fox experiment and still didn't met `inf`, could you provide a reproducible example? (I just fixed a maybe related issue https://github.com/ashawkey/torch-ngp/issues/11, you could try the latest version)
2. You are right, the current simple pytorch rendering function only performs uniform sampling. A better rendering that matches the original repo is still under development.

**Comment by ashawkey** [comment]
Closed for now.
