### ISSUE TITLE
sub-datasets with different perspectives

### ISSUE THREAD

**Issue by heyikou** [ashawkey/torch-ngp#103]
How do I run the code if I have multiple sub-datasets with different perspectives? (putting all the data together takes up too much memory)

**Comment by ashawkey** [comment]
@heyikou Hi, do you mean GPU memory or CPU memory? For GPU OOM, you can turn off `--preload`. For CPU OOM, you may need to modify the data loader (provider.py) to load the image on-the-fly from the hard disk.

**Comment by heyikou** [comment]
@ashawkey Thanks for the reply. My question is, suppose I have 4 sub datasets like image1, image2, image3, image4 and they represent 4 different regions in a large scene. How do I iteratively train them (there are about 1000+ 6000*6000 photos in total)

**Comment by ashawkey** [comment]
That is a really large dataset! I think the only way is to modify the provider to load images on-the-fly from all datasets (unless you have very large CPU memory too). Also, 6000x6000 seems not necessary at the initial training stages. You may try to downsample the images to e.g., 1024x1024.
