### ISSUE TITLE
Training fails when --cuda_ray is turned on (renderer>run_cuda)

### ISSUE THREAD

**Issue by chewry** [ashawkey/torch-ngp#105]
In advance, Thank you for your great work. 

I recently train some data using your code. Without --cuda_ray option, it worked as expected. 
However, if the option is turned on, there is no problem with execution, but training fails. 
(During training, PSNR does not rise from 2dB.)
In detail, using the "run" function instead of the "run_cuda" of renderer.py, the learning was good as before.

If you have experienced this situation or have any guesses about this case, please give me your opinion.

**Comment by ashawkey** [comment]
@chewry This is strange, can you reproduce this problem in other datasets? Or only on a specific dataset?

**Comment by chewry** [comment]
I got the same issue with various scenes.

Looking back, since the scenes are partially dynamic, I put the frame-wise latent code to the density function, similar with [```dnerf renderer.py```](https://github.com/ashawkey/torch-ngp/blob/3c14ad5d1a8a36f8d36604d1bbd91515fb4416fa/dnerf/renderer.py#L299). But I didn't enlarge the density grid to memorize every frame, I left it as-is (```nerf renderer.py```)

I thought the small dynamics in scenes could be learned because it was trained well by ```run```  function (without grid).
But now I think the grid sampling structure (```run_cuda``` function) cannot learn the small dynamics because the structure assumes a completely static scene. (Grid memory cannot be deformed by latent code)

Thanks to your point, my opinion is organized by thinking about which part of my experiment was different.
Do you agree with my guess? I'd appreciate it if you could give me your opinion.

**Comment by chewry** [comment]
I found the reason. In my experiment, the coordinate system follows Blender dataset's (+y: upward, +z: backward).
But in [mask_untrained_grid](https://github.com/ashawkey/torch-ngp/blob/6d5016f34ca9465180dcde68368a62c3294c065f/nerf/renderer.py#L380), positive z area is marked as valid (forward of camera), which is opposite.
The problem is solved.
