### ISSUE TITLE
Not a prime number in the hashencoder

### ISSUE THREAD

**Issue by kecol** [ashawkey/torch-ngp#11]
https://github.com/ashawkey/torch-ngp/blob/56bae6037e68041d7b36024a684177a566f66301/hashencoder/src/hashencoder.cu#L42

One of these numbers is not a prime. This was already fixed in the tiny-cuda-nn repository. And if I remember well the original paper about this hash encoding technique says that the prime numbers used should be big numbers (do not ask me to define big number :D).

BTW: great job you've done here!

**Comment by ashawkey** [comment]
Thanks a lot! I have fixed it in https://github.com/ashawkey/torch-ngp/commit/cfcaed4e3e6db81fa2b08a76b3e9479b24fb5984.
