### ISSUE TITLE
Same camera pose format as Nerf?

### ISSUE THREAD

**Issue by cazhang** [ashawkey/torch-ngp#120]
Just wondering if the camera coordinate the same as nerf?

What I got confused is the use of nerf_to_ngp function in provider?

**Comment by ashawkey** [comment]
@cazhang Hi, no, we use the same coordinate system as instant-ngp.

**Comment by cazhang** [comment]
> @cazhang Hi, no, we use the same coordinate system as instant-ngp.

So nerf_to_ngp conversion is needed if I'm using the nerf-compatible data?

**Comment by ashawkey** [comment]
Yes, but you need to do nothing with the data itself. The data provider will perform the conversion.

**Comment by cazhang** [comment]
I'm using some custom dataset which works with nerf_pytorch, and now want to use it with your torch_ngp, I'm afraid I have to adapt the pose to make it work. My thought is to do the following transform: 
x y z -> x -y -z
is that all I need?
