### ISSUE TITLE
FFMLP performamce

### ISSUE THREAD

**Issue by ashawkey** [ashawkey/torch-ngp#13]
Remind myself to the strange performance of FFMLP in https://github.com/ashawkey/torch-ngp/issues/3#issuecomment-1044047958.

**Comment by JI0726** [comment]
I found the PYTORCH Network (FP32) and the TCNN (FP16) to have similar PSNR and speed performance, is this normal?

**Comment by ashawkey** [comment]
fp32 should be generally slower, but it may depends on your hardware.

**Comment by JI0726** [comment]
I ran it on RTX 3090 GPU, which should be the same as the hardware architecture of the paper. So I find it weird that FP32 and TCNN have the same speed.

**Comment by ashawkey** [comment]
As the performance gain of `ffmlp` is little compared to the native PyTorch MLP, I recommend to always use the more general PyTorch MLP.
