### ISSUE TITLE
The GUI does not display on

### ISSUE THREAD

**Issue by kevinchan04** [ashawkey/torch-ngp#157]
Hi, thank you very much for your opensource! While running the command, I found that the GUI cannot open. However, there is no error notification. Could you give any suggestion to handle this issue?

The command I ran was `python main_nerf.py data/fox --workspace train_nerf_custom --tcnn --gui`

**Comment by kevinchan04** [comment]
Sorry for my fault. I fixed it...

**Comment by wuliAlex** [comment]
I suddenly meet this problem too,could you please tell me how to solve it?
