### ISSUE TITLE
Hi, did you check the gradients of this operators?

### ISSUE THREAD

**Issue by Dengzhi-USTC** [ashawkey/torch-ngp#18]
I try use the torch.autograd.gradcheck to check the analytical and numerical results respectively?
there exists some difference for some random inputs;

Like the following picture
![Selection_199](https://user-images.githubusercontent.com/39289436/155542759-97aca040-63f2-4920-b396-95408a341ee2.png)
;

**Comment by ashawkey** [comment]
No, thanks for mentioning this! Could you tell me which part of code are you testing?

**Comment by Dengzhi-USTC** [comment]
> No, thanks for mentioning this! Could you tell me which part of code are you testing?
I test it in the hash-encoder part, the visualized picture is grad_input, but also for the grad_emddings, if you check, you can print what you want in the torch.autograd. gradcheck and i hope you can check it, later i will test the tiny_cuda code.

Thank you very much;
![Selection_200](https://user-images.githubusercontent.com/39289436/155630999-00792dc5-70c4-4c39-ad19-d8625bf9fe6c.png)

**Comment by ashawkey** [comment]
Thanks, I'll check that.

**Comment by Dengzhi-USTC** [comment]
Hi, can you provide the email, i can sent you the test_code, you can have a try; 
If you are ok, you can sent to my email, my email is the zhideng@mail.ustc.edu.cn;
and I check the tiny_cuda, it is true;

**Comment by ashawkey** [comment]
@Dengzhi-USTC Thanks a lot! It's ashawkey1999@gmail.com; or you can paste it in this issue so it will be automatically sent to my  email.

**Comment by Dengzhi-USTC** [comment]
Thank you very much. I rewrite the code with the tiny_cuda, and i solved this problem.
Later, i will report this;

**Comment by ashawkey** [comment]
Thanks for the testing code! I have verified the problem.
1. For grad_embeddings, there is a problem if input range is not in [0, 1], and this has been fixed in https://github.com/ashawkey/torch-ngp/commit/853dd5188b6b79ad4ebfa909ebaa303311d2f32f.
2. For grad_inputs, since there is still no use case in this repo, I'll focus on it later.
