### ISSUE TITLE
Question about  the scene is bounded in box

### ISSUE THREAD

**Issue by Fangkang515** [ashawkey/torch-ngp#19]
Thanks for your great work. I noticed the following words you said in the readme：
_"Instead of assuming the scene is bounded in the unit box [0, 1] and centered at (0.5, 0.5, 0.5), this repo assumes the scene is bounded in box [-bound, bound], and centered at (0, 0, 0). Therefore, the functionality of aabb_scale is replaced by bound here."_

Is there any consideration for doing this?

**Comment by ashawkey** [comment]
Not really, just a convention decided at first time. Maybe I'll consider changing to the original implementation, since mine has caused some problems in ray marching.

**Comment by ashawkey** [comment]
It seems this will not worsen the rendering quality, closed for now.
