### ISSUE TITLE
Do you also plan to make the wrapper for the MLP part?

### ISSUE THREAD

**Issue by MultiPath** [ashawkey/torch-ngp#2]
What is the major bottleneck in your mind to have the function of fully fusedMLP as the original instant-ngp repo?

**Comment by ashawkey** [comment]
It is much harder since I'm no familiar with WMMA, although I'll try if I have time. Besides, the authors are already working on a [pytorch wrapper](https://github.com/NVlabs/instant-ngp/issues/8#issuecomment-1019792056).

**Comment by MultiPath** [comment]
Thank you
