### ISSUE TITLE
Ray Generation different？

### ISSUE THREAD

**Issue by aoliao12138** [ashawkey/torch-ngp#20]
Hello, torch-ngp is really great work. I really appreciate it! 
It seems that in the origin instant-ngp, for the rays in a batch, they come from different images not from a single image. Also, the number of rays in a batch is not always 4096. It will increase. The origin instant-ngp seems to use image_cdf and error map to help the ray sampling. I think adding this part may increase the performance and speed of torch-ngp. Any plan for this? Thank you very much!

**Comment by ashawkey** [comment]
Thanks for the advice! I am still trying to verify the influence of each part, and will implement these features if it does help (although it may take some time...)

**Comment by ashawkey** [comment]
I have done ablation on these options, and found that none of these will influence the rendering quality in a significant way. BTW, for blender dataset, the rendering quality gap is mainly from dataset splits. Please try the newest commit!
