### ISSUE TITLE
hashencoder.cu error with some specific gpu models

### ISSUE THREAD

**Issue by gukai330** [ashawkey/torch-ngp#22]
Thank you for your work!

Had this issue when I am running your code on the server with different GPU models, the script failed when running with some specific GPU models (like tesla P100,), but worked fine with some other GPU models(like tesla v100)

hashencoder.cu(25): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (__half *, c10::Half)

ninja: build stopped: subcommand failed.

cuda version: 11.3.1
cudnn version: 8.2.0.53

**Comment by gukai330** [comment]
I find the issue in  instant ngp [#52](https://github.com/NVlabs/instant-ngp/issues/52)),
I am trying with the solution

**Comment by ashawkey** [comment]
I'm not sure if it is related to windows, but this error message does come from low GPU arch.

**Comment by ashawkey** [comment]
You can check the CUDA programming guide [here](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html):
`The 16-bit __half floating-point version of atomicAdd() is only supported by devices of compute capability 7.x and higher.`

**Comment by gukai330** [comment]
> 



> I'm not sure if it is related to windows, but this error message does come from low GPU arch.
thank you, I made a mistake about the issue, thank you for your explanation.

**Comment by gukai330** [comment]
> I'm not sure if it is related to windows, but this error message does come from low GPU arch.

thank you for your explanation, I misunderstand the error message. this should have nothing to do with windows
