### ISSUE TITLE
Insufficient hash resolution harming performance

### ISSUE THREAD

**Issue by xmk2222** [ashawkey/torch-ngp#23]
I noticed that the `desired_resolution` of hash encoding is fixed in torch-ngp: 
https://github.com/ashawkey/torch-ngp/blob/9e224d9bfb7b2deb4241717fa6805c2877939bb4/nerf/network.py#L26

https://github.com/ashawkey/torch-ngp/blob/9e224d9bfb7b2deb4241717fa6805c2877939bb4/encoding.py#L52

While in instant-ngp, it is a parameter controlled by `aabb_scale`. When `aabb_scale` == 1, the `desired_resolution` = 2048, and when `aabb_scale` increases to 16, the `desired_resolution` increases to 32768. (The `per_level_scale` changes, too.)

That proved to be a huge gap on performance (also memory) in my trial, which is on a rather big scene than lego.

**Comment by ashawkey** [comment]
Thanks for reporting this. According to [this line](https://github.com/NVlabs/instant-ngp/blob/af549ad86371c045310439f1fc505976d42c7fa2/src/testbed.cu#L1645), `desired_resolution` should be linearly scaled with `aabb_scale`  (`bound` in this implmentaiton).
Another problem is that we don't have a multi-scale density grid, and exponential ray marching is not supported, which may lead to worse performance too.
However, currently I don't have a dataset large enough to test these changes, could you share the dataset name if it is openly available?

**Comment by aoliao12138** [comment]
[NHR](https://wuminye.github.io/NHR/) provides a multiview dataset for humans.

**Comment by ashawkey** [comment]
@xmk2222 I have added the scaling in https://github.com/ashawkey/torch-ngp/commit/086b15c055e1dfed3e883fb248995441b5fb5ff4, but on a naive test with lego (bound=16, scale=10), the results are still blurry. Maybe you could test on your dataset again?

**Comment by xmk2222** [comment]
@ashawkey Thanks! That is exactly what I meant. I will test it later.

However, I think there are some differences still: 
In `instant-ngp`, the condition is:
- `aabb_scale`: 16
- `desired_resolution`: 32768,
- `bounding_box`:  [-7.5, 8.5];

But in `torch-ngp`:
- `bound`: 16
- `desired_resolution`: 32768 (same as in i-ngp)
- `bounding_box`: [-16, 16] which is different from the scale of in i-ngp.

The corresponding code in instant-ngp:

https://github.com/NVlabs/instant-ngp/blob/692ce14f4f154c03c5784a944c625da94b08e292/src/testbed_nerf.cu#L2293:L2294

In my trial, the hash encoding has some tolerence in scaling, but maybe it would be better to strictly align with i-ngp, at least in scaling?

**Comment by ashawkey** [comment]
@xmk2222 You are right, this is a difference from instant-ngp. However, although we assumes the scene is twice larger in length, we also twice the min step size in ray marching [here](https://github.com/ashawkey/torch-ngp/blob/main/raymarching/src/raymarching.cu#L24). So it shouldn't affect much as long as `bound` is the same as `aabb_scale`.

**Comment by ashawkey** [comment]
As the cascaded density grid has been implemented, I'll close this for now.
