### ISSUE TITLE
Do we need separate network for coarse and fine sampling

### ISSUE THREAD

**Issue by yangze0930** [ashawkey/torch-ngp#24]
In NeRF's original paper, they are optimizing two separate networks for coarse and fine samples in hierarchical sampling. In this repo, I found only a single model is used to compute density/radiance for both coarse and fine samples.

https://github.com/ashawkey/torch-ngp/blob/65a940835846908beb527d576e88a310ae977ee2/nerf/renderer.py#L155
https://github.com/ashawkey/torch-ngp/blob/65a940835846908beb527d576e88a310ae977ee2/nerf/renderer.py#L181

Do we need separate network for coarse and fine samples? Or the Hash encoding allows us to model the coarse and fine samples with a single network?

**Comment by ashawkey** [comment]
Thsi repo follows the implementation of instant-ngp, which only uses one network. Besides, hierarchical sampling is not used in instant-ngp's ray marching (`--cuda_ray` mode in this repo).

**Comment by ashawkey** [comment]
Closed if no other problems.
