### ISSUE TITLE
Generate the nan when training the nerf for the cuda_ray.

### ISSUE THREAD

**Issue by Dengzhi-USTC** [ashawkey/torch-ngp#28]
![Selection_315](https://user-images.githubusercontent.com/39289436/158553884-ae45d4a2-1a19-4c49-8249-ad9a91d86068.png)

Will be normal after some epochs. Can you explain this?

![Selection_316](https://user-images.githubusercontent.com/39289436/158554068-ae9fc8a4-b786-41cc-8f5d-a7a5ab864ecd.png)

**Comment by ashawkey** [comment]
emmm are you using `--fp16`? Still, could you provide more a reproducible example?

**Comment by Dengzhi-USTC** [comment]
I use the lego example from the Nerf; may be the learn-rate is not suitable;

**Comment by jamie-reconlabs** [comment]
I'm having the same issue with a custom dataset. If the issue is closed, what was the solution?
