### ISSUE TITLE
CUDA Issues running NeRF example

### ISSUE THREAD

**Issue by javieryu** [ashawkey/torch-ngp#31]
Running into some issues running the nerf example.

![Screenshot from 2022-03-17 09-41-49](https://user-images.githubusercontent.com/17129398/158850525-48d2657d-52ab-40c9-871f-7d0ee584226b.png)

My setup is:
OS: Ubuntu 20.04
GPU: RTX 3070 Ti 
CUDA: 11.6 (driver 510)

Pretty sure CUDA is install correctly and I've added these lines to my `.zshrc`:
`export PATH="/usr/local/cuda-11.6/bin:$PATH"`
`export LD_LIBRARY_PATH="/usr/local/cuda-11.6/lib64:$LD_LIBRARY_PATH"`

**Comment by ashawkey** [comment]
Hi, this seems not to be a problem of this repo. Could you install other pytorch extensions, like the `tiny-cuda-nn` (`pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch`)?
A related issue [here](https://github.com/pytorch/extension-cpp/issues/71) maybe helpful.

**Comment by javieryu** [comment]
Solved, I was trying to run the code with CUDA related flags that were not compatible with my GPU. Removing the `CUDA_VISIBLE_DEVICES=1` from the `run_nerf.sh` script solved this issue.
