### ISSUE TITLE
Strange performance when using --tcnn mode

### ISSUE THREAD

**Issue by JasonLSC** [ashawkey/torch-ngp#32]
Hi, have you reproduced the PSNR performance in "--tcnn" mode since the latest commit?

In my experiment of "Lego", the training&test PSNR in "--tcnn" mode is quite strange, only 23+ dB , while the PSNR in "--ff --fp16" mode is about 28+dB. 

My command line for training in "--tcnn" mode is `python main_nerf.py data/nerf_synthetic/lego --workspace exp/lego_tcnn --tcnn --mode blender --bound 1 --scale 0.8
`
Did I miss something in the command line?

**Comment by ashawkey** [comment]
@JasonLSC Hi, you should add `--fp16` for `--tcnn`, this has been fixed in https://github.com/ashawkey/torch-ngp/commit/f9bf311df69f96afb22857c88cbf7eb821a0685e.
