### ISSUE TITLE
How much progress in the past few weeks?

### ISSUE THREAD

**Issue by tahsd** [ashawkey/torch-ngp#33]
Hi, I am interested in INGP paper, but have been struggling with the official code which is c++ based.
Therefore I was glad that there existed a Pytorch implementation as you have provided, 
but a while ago I couldn't help sticking with the official one, because yours seemed to have issues with its performance.

So I wonder how much you have narrowed the gap between your work and the official one, in terms of PSNR and training/inference time.

Your work contributes a lot, thanks!

**Comment by ashawkey** [comment]
Hi, you could check the readme (update logs part) for the progress. Since an exact reproduction is hard, there is still a large gap from the original implementaiton, e.g., PSNR for lego is ~33 compared to ~35, and speed is 2-5x slower.
