### ISSUE TITLE
About the zeros-initization of the hash-grid;

### ISSUE THREAD

**Issue by Dengzhi-USTC** [ashawkey/torch-ngp#35]
Hi
I find the zeros-initilization of the hash-grid in the Sec.4 IMPLEMENTATION is works; (I need those special initialization in my experiment setting)
but i test your code, it not work;
can you explain it? thank you

**Comment by ashawkey** [comment]
@Dengzhi-USTC The density output activation function is default to `relu`, which will make all-zero initialization fail to propagate, while the original implementation uses `exponential`. However, I haven't succeeded in using `exp` as the output activation. I recommend you try `softplus`.

**Comment by Dengzhi-USTC** [comment]
Thank you very much
it works;
