### ISSUE TITLE
results on real sences

### ISSUE THREAD

**Issue by cv-lab-x** [ashawkey/torch-ngp#36]
Hi, thanks for your great work. i have a little question about the results on real sences. Did you test the network on some real sences for example DTU or Tanks and Temples datasets?
looking forward to your reply, thanks a lot!

**Comment by ashawkey** [comment]
I think the fox dataset is a real scene? Currently only nerf-compatible dataset format is supported as in instant-ngp, however, you can always implement it yourself.

**Comment by ashawkey** [comment]
closed for now.
