### ISSUE TITLE
Support batch-based hash grid?

### ISSUE THREAD

**Issue by StevenLiuWen** [ashawkey/torch-ngp#37]
Hi, thanks a lot for this great work.

I wonder whether it is possible to support the batch-based hash grid? 

Currently, it seems that the hash grid (as well as the [hash embeddings](https://github.com/ashawkey/torch-ngp/blob/main/hashencoder/hashgrid.py#L115)) is **#offsets x level_dim.** In many tasks, hash embeddings with **B x #offsets x level_dim** might be helpful. 

A naive implementation might be for-loop the batch-dim of the hash grid in https://github.com/ashawkey/torch-ngp/blob/main/hashencoder/hashgrid.py#L137, while this approach might be more inefficient than the cuda kernel implementation. 

Thanks for your reply.

**Comment by ashawkey** [comment]
This is a good idea, but for this repo we don't have a batched reconstruction use case right now, and the original instant-ngp is designed to train on only one scene at once. Therefore, this feature may not be added here, but you can try to implement it yourself.

**Comment by StevenLiuWen** [comment]
Got it, thanks.

**Comment by ashawkey** [comment]
closed for now.
