### ISSUE TITLE
significantly downgraded performance when enabling `--ff` and `--cuda_ray`

### ISSUE THREAD

**Issue by Karbo123** [ashawkey/torch-ngp#38]
Thanks for creating this great work! But, however, I found that the performance will be significantly downgraded if we enable `--ff` or `--cuda_ray`. Here are some testing results.
``` bash
CUDA_VISIBLE_DEVICES=0 python main_nerf.py data/fox --workspace trial_nerf
==> 16 ~ 17 it/s

CUDA_VISIBLE_DEVICES=0 python main_nerf.py data/fox --workspace trial_nerf --cuda_ray
==> 12 ~ 13 it/s

CUDA_VISIBLE_DEVICES=0 python main_nerf.py data/fox --workspace trial_nerf --fp16
==> 26 ~ 27 it/s

CUDA_VISIBLE_DEVICES=0 python main_nerf.py data/fox --workspace trial_nerf --fp16  --cuda_ray
==> 21 ~ 22 it/s

CUDA_VISIBLE_DEVICES=0 python main_nerf.py data/fox --workspace trial_nerf --fp16  --cuda_ray --ff
==> 9 ~ 10 it/s
```
My environment is `torch=1.8.0` and `cuda=11.2` with a `RTX-3090` card.

I originally expect that the performance will be futher improved if I enable these options, but actually it doesn't.
Could you give me some suggestions to improve this strange phenomenon? Thank you!

**Comment by Karbo123** [comment]
Yes, enabling `--cuda_ray` option in the latest commit (873c267) indeed increase the performance a bit. However, I also notice that if we enable `--ff`, the performance will downgrade slightly which is unexpected.
Here I give some test results.
```
CUDA_VISIBLE_DEVICES=2 python main_nerf.py data/fox --workspace trial_nerf --fp16 --ff --cuda_ray
==> 22 ~ 23 it/s

CUDA_VISIBLE_DEVICES=2 python main_nerf.py data/fox --workspace trial_nerf --fp16 --ff
==> 11 ~ 12 it/s

CUDA_VISIBLE_DEVICES=2 python main_nerf.py data/fox --workspace trial_nerf --fp16 
==> 22 ~ 23 it/s

CUDA_VISIBLE_DEVICES=2 python main_nerf.py data/fox --workspace trial_nerf 
==> 14 ~ 15 it/s

CUDA_VISIBLE_DEVICES=2 python main_nerf.py data/fox --workspace trial_nerf --cuda_ray
==> 30 ~ 33 it/s
```

**Comment by ashawkey** [comment]
@Karbo123 On my TITAN RTX I got similar performance (16-17it/s) on fox with or without `--ff`. 
This has been mentioned earlier https://github.com/ashawkey/torch-ngp/issues/3#issuecomment-1043292792, but unfortunately I don't have a 3090 to test. 
Maybe you could just use the native `--fp16`, since it gives best performance.
