### ISSUE TITLE
Why is "--fp16" mandatory to the "--tcnn" and "--ff" mode?

### ISSUE THREAD

**Issue by JasonLSC** [ashawkey/torch-ngp#39]
Hi, thank you for your great implementation and progressive updates. 

I wonder why "--fp16" is mandatory to the "--tcnn" and "--ff" mode?
And I found the "dtype" of parameters (eg. Hash Feature Values) in model  is 'float32' when I was debuging, is it correct?
Does "--fp16" mean that the calculation in CUDA backend  is operated in ‘float16’？

**Comment by ashawkey** [comment]
@JasonLSC Yes, pytorch's native mixed precision training doesn't affect parameters' data type, it only happens at the forward and backward call (you can refer to the official [doc](https://pytorch.org/docs/stable/amp.html)). In particular, the implementation of fully-fused MLP requires half precision, e.g., [here](https://github.com/NVlabs/tiny-cuda-nn/blob/master/src/fully_fused_mlp.cu#L48).
