### ISSUE TITLE
kernel_composite_weights_backward

### ISSUE THREAD

**Issue by Kyrie-Irving07** [ashawkey/torch-ngp#40]
Hi, thank you for an excellent implementation of instant-ngp in pytorch!

I notice that in kernel_composite_weights_backward function in raymarching/raymarching.cu,  the gradient of sigma is calculated as:
grad_sigmas[0] = grad_weights[0] * deltas[0].

We know that **weight_i = T_i * alpha_i = T_i * (1 - exp(-delta_i * sigma_i))**, thus **grad_sigmas_i = \sum_{j>=i} grad_weight_j * grad_weight_j_to_sigmas_i = (\sum_{j>i} - delta_i * grad_weight_j) + T_i * delta_i * exp(-delta_i * sigma_i)**

So is that correct to let grad_sigmas[0] = grad_weights[0] * deltas[0]?

**Comment by ashawkey** [comment]
@Kyrie-Irving07 In fact here the `grad_weights` is not really dL/dw. It is just an intermediate result to calculate `grad_sigmas`, to avoid the \sum_{j >= i} step (which will be O(n^2)). 
The original formula to calculate `grad_sigmas` is from [instant-ngp](https://github.com/NVlabs/instant-ngp/blob/master/src/testbed_nerf.cu#L1426), I just separated it into two parts here.

**Comment by Kyrie-Irving07** [comment]
Got it~ thx : )
