### ISSUE TITLE
problem when enable "cuda_ray" for rendering

### ISSUE THREAD

**Issue by Holmes-Alan** [ashawkey/torch-ngp#41]
I met the problem when I enable "--cuda_ray" for rendering as follows.

C:\Users\Miniconda3\envs\ngp\lib\site-packages\torch\include\pybind11\cast.h(1503): error: too few arguments for template template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
(1507): here
C:\Users\Miniconda3\envs\ngp\lib\site-packages\torch\include\pybind11\cast.h(1503): error: too few arguments for template template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
(1507): here
.....
2 errors detected in the compilation of "D:/torch-ngp/raymarching/src/raymarching.cu".
raymarching.cu
ninja: build stopped: subcommand failed.

The problem seems to be from the pybind11. Can someone help me out? Thanks in advance.

**Comment by ashawkey** [comment]
Could you give more information about the environment? e.g., OS, pytorch version, CUDA version? 
I would recommend using a Linux system, such as WSL on if you are using Windows.

**Comment by ashawkey** [comment]
@Holmes-Alan Hi, I have tested on Windows and added support in the latest commit. You can try again.
