### ISSUE TITLE
I have some questions that I hope will be answered

### ISSUE THREAD

**Issue by XJTU-JP** [ashawkey/torch-ngp#42]
Here is my environment configuration
`GPU number is  2`
`GPU =  NVIDIA GeForce RTX 2080 Ti`
`cuda is available ?  True`
`torch.version.cuda =  10.2`
`torch.version =  1.11.0+cu102`

But I am getting strange exception when running

`  File "main_nerf.py", line 55, in <module>`
   ` from nerf.network import NeRFNetwork`
  `File "/home/jiangpeng/Work/torch-ngp/nerf/network.py", line 5, in <module>`
  `  from encoding import get_encoder`
 ` File "/home/jiangpeng/Work/torch-ngp/encoding.py", line 6, in <module>`
   ` from shencoder import SHEncoder`
  `File "/home/jiangpeng/Work/torch-ngp/shencoder/__init__.py", line 1, in <module>`
   ` from .sphere_harmonics import SHEncoder`
  `File "/home/jiangpeng/Work/torch-ngp/shencoder/sphere_harmonics.py", line 9, in <module>`
  `  from .backend import _backend`
 ` File "/home/jiangpeng/Work/torch-ngp/shencoder/backend.py", line 9, in <module>`
  `  sources=[os.path.join(_src_path, 'src', f) for f in [`
 ` File "/home/jiangpeng/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1156, in load`
   ` keep_intermediates=keep_intermediates)`
 ` File "/home/jiangpeng/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1371, in _jit_compile`
    `baton.wait()`
  `File "/home/jiangpeng/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/utils/file_baton.py", line 42, in wait`
    `time.sleep(self.wait_seconds)`

Why does the program go to sleep

**Comment by ashawkey** [comment]
@XJTU-JP Hi, I think it is a normal behavior at building the extension according to [here](https://github.com/pytorch/pytorch/blob/master/torch/utils/cpp_extension.py#L1391), have you tried to wait until it finish?
If it cannot finish, you could check if you can write to the `build_directory`, which is 
> ``<tmp>/torch_extensions/<name>``, where ``<tmp>`` is the temporary folder on the current platform and ``<name>`` the name of the extension. 

according to the pytorch doc.

**Comment by XJTU-JP** [comment]
yes you are right i waited an extra minutet,hank you
