### ISSUE TITLE
How can i apply smoothstep function in this repo

### ISSUE THREAD

**Issue by ggrp-china** [ashawkey/torch-ngp#44]
@ashawkey Thanks for your great work!
I see that  [readme](https://github.com/ashawkey/torch-ngp/blob/main/readme.md) said this repo only implement the linear interpolation mode ，and A low-cost smoothstep function is provided in Appendix A of the [paper](moz-extension://f07c8908-2749-4e92-9fe1-08b39fdb8b90/pdf-viewer/web/viewer.html?file=https%3A%2F%2Fnvlabs.github.io%2Finstant-ngp%2Fassets%2Fmueller2022instant.pdf).
If I want to apply it in this repo, where do I need to add it, is it [here](https://github.com/ashawkey/torch-ngp/blob/bfd52871a7638fe743242d7ac131c3b101ed9d8c/hashencoder/src/hashencoder.cu#L139) `hashencoder.cu` ?

**Comment by ggrp-china** [comment]
@ashawkey Thanks for the detailed instructions！I'll try what you said.
Thank you again for your great work, your work gave me an initial understanding of the cuda language！

**Comment by ashawkey** [comment]
Glad to hear that! Closed for now.
