### ISSUE TITLE
the GUI can‘t work

### ISSUE THREAD

**Issue by alittle-cike** [ashawkey/torch-ngp#46]
Hello, when using the GUI, the screen is very stuck, and I can't observe the rendering effect. I have two GPUs in my computer, I don't know if this is the reason? Do I need to disable one of the GPUs?

**Comment by ashawkey** [comment]
@alittle-cike Hi, by "screen" do you mean just the GUI window, or the whole system screen?
If it is the GUI window, could you provide some details about your environment, such as the GPU arch? You may also check if it can run successfully in CMD mode, a speed reference is provided in readme.
If it is the system screen, you can specify which GPU to use by something like `CUDA_VISIBLE_DEVICES=1 python ...` (assuming in Linux) and check again.

**Comment by XJTU-JP** [comment]
environment:cuda=11.3, pytorch=1.11，ubuntu20.
I mean when i test the fox in the GUI window, 
I can't change the viewing angle (or it's very stuck when moving the viewing angle).
I have two GPUs=RTX2080TI.
when i use no-gui (CMD) mode, it's can work.
Thank you for your answer.

**Comment by alittle-cike** [comment]
yes,I mean that GUI windows are very stuck, both before and after training.
I use the lego data,
`CUDA_VISIBLE_DEVICES=0 python main_nerf.py data/lego --workspace trial_nerf --mode blender --gui --radius 1`
When the training starts, I try to move the angle to view the 3D model, 
but the GUI window is very stuck (it looks like the FPS is very low) and I can't move.

i have two GPUs=RTX2080TI,
----------------------------------------------------------------------------------------------------------------------
Device 0: "NVIDIA GeForce RTX 2080 Ti"
  CUDA Driver Version / Runtime Version          11.4 / 11.3
  CUDA Capability Major/Minor version number:    7.5
  Total amount of global memory:                 11019 MBytes (11554717696 bytes)
  (068) Multiprocessors, (064) CUDA Cores/MP:    4352 CUDA Cores
  GPU Max Clock rate:                            1545 MHz (1.54 GHz)
  Memory Clock rate:                             7000 Mhz
  Memory Bus Width:                              352-bit
  L2 Cache Size:                                 5767168 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total shared memory per multiprocessor:        65536 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1024
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 3 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Managed Memory:                Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 23 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

Device 1: "NVIDIA GeForce RTX 2080 Ti"
  CUDA Driver Version / Runtime Version          11.4 / 11.3
  CUDA Capability Major/Minor version number:    7.5
  Total amount of global memory:                 11016 MBytes (11551440896 bytes)
  (068) Multiprocessors, (064) CUDA Cores/MP:    4352 CUDA Cores
  GPU Max Clock rate:                            1545 MHz (1.54 GHz)
  Memory Clock rate:                             7000 Mhz
  Memory Bus Width:                              352-bit
  L2 Cache Size:                                 5767168 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total shared memory per multiprocessor:        65536 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1024
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 3 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Managed Memory:                Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 101 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >
> Peer access from NVIDIA GeForce RTX 2080 Ti (GPU0) -> NVIDIA GeForce RTX 2080 Ti (GPU1) : No
> Peer access from NVIDIA GeForce RTX 2080 Ti (GPU1) -> NVIDIA GeForce RTX 2080 Ti (GPU0) : No
------------------------------------------------------------------------------------------------------------------------------------------------
thank you

**Comment by ashawkey** [comment]
Hi,
You should add `--cuda_ray` at least for GUI mode. For 2080ti, installing
tiny-cuda-nn and further append `--tcnn` will improve the performance
further. Please check the readme for more details.
BTW, it seems I cannot see your comment in github issue, but only in my
email inbox. Just reply in the github issue is OK.

Best regards,
kiui

**Comment by ashawkey** [comment]
You can refer to the `aabb_scale` if you have used instant-ngp. Basically, you should `scale` down the camera to make it falls just inside `bound` box. If `scale` > 1, it will also use adaptive ray marching to further accelerate training, which could be controlled by `--dt_gamma`. Also check the readme.
