### ISSUE TITLE
some black fog on the test results

### ISSUE THREAD

**Issue by QAZWSX0827** [ashawkey/torch-ngp#48]
hi, thank you very much for your work.

I have one question,when I was training, I had a 34+ PSNR，But this is what happened when I tested a new pose.

https://user-images.githubusercontent.com/63493274/162655669-09784b3a-ca72-4b20-9aef-8ff5d7f68d8a.mp4

In addition, I ran the original NeRF with the same data and got better results as follows

https://user-images.githubusercontent.com/63493274/162655815-b73fa03d-7b16-4f87-88a6-e7236819150a.mp4

I tried tweaking the parameters "bound" and "scale" but the results didn't improve.

What the reason behind this result do you think?

Many thanks.

**Comment by ashawkey** [comment]
@QAZWSX0827 Have you tried the GUI to see exactly where goes wrong? How long have you trained? 
BTW, if this piece of data is openly available, I would be happy to test it.

**Comment by QAZWSX0827** [comment]
I use a remote server to run your program, so IT's hard for me to use the GUI.

I trained 1000 epochs. 

This dataset is a private dataset and therefore cannot be sent out.

**Comment by ashawkey** [comment]
That's OK. Could you provide the detailed parameters then? And have you tried the official instant-ngp?

**Comment by QAZWSX0827** [comment]
“--fp16 --bound 3.6 --scale 2 --mode blender” 

other parameters are default.

I haven't tried the official instant-ngp.

**Comment by ashawkey** [comment]
So why are you not using the faster `--cuda-ray`? what about `--fp16 --cuda_ray --bound 1.0 --scale 0.33 --mode blender`? This should disable the adaptive ray marching which is only experimental.

**Comment by QAZWSX0827** [comment]
#21 
because in issue 21 you said"Currently, to improve quality (at the cost of speed), you can remove --cuda_ray, and enlarge --num_steps and --upsample_steps to use the pytorch ray marching."
I think I might get a better result if I removed "cuda_ray".

BTW，I don't understand the meaning of this sentence ”This should disable the adaptive ray marching which is only experimental.“

I'll try your parameters now.I also have a question that What's the trick for determining scale and bound？

**Comment by ashawkey** [comment]
1. That was a very early version, and the problem is already fixed. Please check the readme for a performance reference. 
2. If you have checked the original instant-ngp, it use different step size based on the distance to scene center, which could boost speed in CUDA raymarching. However, this may lead to worse performance since sampled points per ray also decrease.
3. If you can use the GUI, it will be easy to determine this parameters by some trial-and-error. Basically, `scale` down the camera so it falls just inside `bound` is the best choice.

**Comment by QAZWSX0827** [comment]
So you mean I should add "--cuda_ray"?
Because the "bound = 3.6" and "scale = 2" are the ones with the higher PSNR after the experiment.
I tried ”--bound 1.0 --scale 0.33 “, but it didn't work very well.

**Comment by ashawkey** [comment]
Yes, please check the readme first.
It's hard for me to debug something I cannot reproduce... Have you tried the provided examples, and how do they look like?

**Comment by QAZWSX0827** [comment]
I'm sorry that I may have been looking at a previous version of readme,Lego's results were good
![ngp_0300_0160](https://user-images.githubusercontent.com/63493274/162697296-c90374c8-80fc-4752-a54d-3d7a17046f20.png)

**Comment by ashawkey** [comment]
This is NOT good... are you using the latest version? and use the correct script:
```bash
python main_nerf.py data/nerf_synthetic/lego --workspace trial_nerf_lego_ff2 --fp16 --ff --cuda_ray --bound 1.0 --scale 0.8 --dt_gamma 0 --mode blender
```
You are expected to get something like this:
![image](https://user-images.githubusercontent.com/25863658/162699376-d14e7f29-d615-4954-a6cd-82d5a51c9580.png)

**Comment by QAZWSX0827** [comment]
It's actually the late March version，I'll try your latest version now.

But "-- ff" seems to take a long time
