### ISSUE TITLE
ff and cuda_ray flag

### ISSUE THREAD

**Issue by QinlongHuang** [ashawkey/torch-ngp#49]
Nice job! But what does the flag 'ff' and 'cuda_ray' mean ?
Does ff mean an implenment of tcnn yourself ?
What about cuda_ray ? Sampling ray with CUDA ops?

**Comment by ashawkey** [comment]
@QinlongHuang Yes, these can be found in the readme.

**Comment by QinlongHuang** [comment]
@ashawkey Thanks for your reply.
And one more question. Is there any difference between SHEncoder or HashEncoder in this repo and tinycudann.Encoding ? Because I have test these two implementation, and find something different.

**Comment by ashawkey** [comment]
There may be implementation differences, but the idea behind the algorithm should be the same, and the performance are similar.
