### ISSUE TITLE
Gigapixel Image Approximation Experiment in instant-ngp

### ISSUE THREAD

**Issue by JI0726** [ashawkey/torch-ngp#50]
Recently I tried to put this code into a video coding task ((x,y,t)->(r, g,b)), which is similar to SDF task, but the effect is not ideal, so I tried the  Gigapixel Image Approximation experiment  in the paper, and found that it cannot be reproduced under the same experimental setting. Has anyone ever encountered the same problem yet？

**Comment by ashawkey** [comment]
For Gigapixel Image exp, I would recommend using tiny-cuda-nn's example: https://github.com/NVlabs/tiny-cuda-nn/blob/master/samples/mlp_learning_an_image_pytorch.py

**Comment by JI0726** [comment]
> For Gigapixel Image exp, I would recommend using tiny-cuda-nn's example: https://github.com/NVlabs/tiny-cuda-nn/blob/master/samples/mlp_learning_an_image_pytorch.py

Ok, thanks a lot.
