### ISSUE TITLE
Error building extension '_raymarching'

### ISSUE THREAD

**Issue by francescofugazzi** [ashawkey/torch-ngp#51]
I get this when tryin to launch the example for the first time

Traceback (most recent call last):
  File "C:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\utils\cpp_extension.py", line 1740, in _run_ninja_build
    subprocess.run(
  File "C:\Users\franz\anaconda3\envs\torchngp\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\nvidia\torch-ngp\main_nerf.py", line 63, in <module>
    from nerf.network import NeRFNetwork
  File "E:\nvidia\torch-ngp\nerf\network.py", line 7, in <module>
    from .renderer import NeRFRenderer
  File "E:\nvidia\torch-ngp\nerf\renderer.py", line 9, in <module>
    import raymarching
  File "E:\nvidia\torch-ngp\raymarching\__init__.py", line 1, in <module>
    from .raymarching import *
  File "E:\nvidia\torch-ngp\raymarching\raymarching.py", line 9, in <module>
    from .backend import _backend
  File "E:\nvidia\torch-ngp\raymarching\backend.py", line 31, in <module>
    _backend = load(name='_raymarching',
  File "C:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\utils\cpp_extension.py", line 1144, in load
    return _jit_compile(
  File "C:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\utils\cpp_extension.py", line 1357, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\utils\cpp_extension.py", line 1469, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "C:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\utils\cpp_extension.py", line 1756, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension '_raymarching': [1/2] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc --generate-dependencies-with-compile --dependency-output raymarching.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=_raymarching -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include -IC:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include\TH -IC:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include" -IC:\Users\franz\anaconda3\envs\torchngp\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -c E:\nvidia\torch-ngp\raymarching\src\raymarching.cu -o raymarching.cuda.o
FAILED: raymarching.cuda.o
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc --generate-dependencies-with-compile --dependency-output raymarching.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=_raymarching -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include -IC:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include\TH -IC:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include" -IC:\Users\franz\anaconda3\envs\torchngp\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -c E:\nvidia\torch-ngp\raymarching\src\raymarching.cu -o raymarching.cuda.o
cl : warning della riga di comando D9025 : override di '/D__CUDA_NO_HALF_OPERATORS__' con '/U__CUDA_NO_HALF_OPERATORS__'
cl : warning della riga di comando D9025 : override di '/D__CUDA_NO_HALF_CONVERSIONS__' con '/U__CUDA_NO_HALF_CONVERSIONS__'
cl : warning della riga di comando D9025 : override di '/D__CUDA_NO_HALF2_OPERATORS__' con '/U__CUDA_NO_HALF2_OPERATORS__'
raymarching.cu
C:/Users/franz/anaconda3/envs/torchngp/lib/site-packages/torch/include\c10/macros/Macros.h(142): warning C4067: token imprevisti dopo una direttiva per il preprocessore. Previsto un carattere di nuova riga
cl : warning della riga di comando D9025 : override di '/D__CUDA_NO_HALF_OPERATORS__' con '/U__CUDA_NO_HALF_OPERATORS__'
cl : warning della riga di comando D9025 : override di '/D__CUDA_NO_HALF_CONVERSIONS__' con '/U__CUDA_NO_HALF_CONVERSIONS__'
cl : warning della riga di comando D9025 : override di '/D__CUDA_NO_HALF2_OPERATORS__' con '/U__CUDA_NO_HALF2_OPERATORS__'
raymarching.cu
C:/Users/franz/anaconda3/envs/torchngp/lib/site-packages/torch/include\c10/macros/Macros.h(142): warning C4067: token imprevisti dopo una direttiva per il preprocessore. Previsto un carattere di nuova riga
C:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include\pybind11\cast.h(1429): error: too few arguments for template template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
(1507): here

C:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include\pybind11\cast.h(1503): error: too few arguments for template template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
(1507): here

E:\nvidia\torch-ngp\raymarching\src\raymarching.cu(332): warning #177-D: variable "index" was declared but never referenced
          detected during instantiation of "void kernel_composite_weights_forward(const scalar_t *, const scalar_t *, const int *, uint32_t, uint32_t, scalar_t *) [with scalar_t=double]"
(626): here

E:\nvidia\torch-ngp\raymarching\src\raymarching.cu(332): warning #177-D: variable "index" was declared but never referenced
          detected during instantiation of "void kernel_composite_weights_forward(const scalar_t *, const scalar_t *, const int *, uint32_t, uint32_t, scalar_t *) [with scalar_t=float]"
(626): here

E:\nvidia\torch-ngp\raymarching\src\raymarching.cu(332): warning #177-D: variable "index" was declared but never referenced
          detected during instantiation of "void kernel_composite_weights_forward(const scalar_t *, const scalar_t *, const int *, uint32_t, uint32_t, scalar_t *) [with scalar_t=c10::Half]"
(626): here

E:\nvidia\torch-ngp\raymarching\src\raymarching.cu(407): warning #177-D: variable "weight" was declared but never referenced
          detected during instantiation of "void kernel_composite_weights_backward(const scalar_t *, const scalar_t *, const scalar_t *, const int *, uint32_t, uint32_t, const scalar_t *, scalar_t *) [with scalar_t=double]"
(659): here

E:\nvidia\torch-ngp\raymarching\src\raymarching.cu(389): warning #177-D: variable "index" was declared but never referenced
          detected during instantiation of "void kernel_composite_weights_backward(const scalar_t *, const scalar_t *, const scalar_t *, const int *, uint32_t, uint32_t, const scalar_t *, scalar_t *) [with scalar_t=double]"
(659): here

E:\nvidia\torch-ngp\raymarching\src\raymarching.cu(407): warning #177-D: variable "weight" was declared but never referenced
          detected during instantiation of "void kernel_composite_weights_backward(const scalar_t *, const scalar_t *, const scalar_t *, const int *, uint32_t, uint32_t, const scalar_t *, scalar_t *) [with scalar_t=float]"
(659): here

E:\nvidia\torch-ngp\raymarching\src\raymarching.cu(389): warning #177-D: variable "index" was declared but never referenced
          detected during instantiation of "void kernel_composite_weights_backward(const scalar_t *, const scalar_t *, const scalar_t *, const int *, uint32_t, uint32_t, const scalar_t *, scalar_t *) [with scalar_t=float]"
(659): here

E:\nvidia\torch-ngp\raymarching\src\raymarching.cu(407): warning #177-D: variable "weight" was declared but never referenced
          detected during instantiation of "void kernel_composite_weights_backward(const scalar_t *, const scalar_t *, const scalar_t *, const int *, uint32_t, uint32_t, const scalar_t *, scalar_t *) [with scalar_t=c10::Half]"
(659): here

E:\nvidia\torch-ngp\raymarching\src\raymarching.cu(389): warning #177-D: variable "index" was declared but never referenced
          detected during instantiation of "void kernel_composite_weights_backward(const scalar_t *, const scalar_t *, const scalar_t *, const int *, uint32_t, uint32_t, const scalar_t *, scalar_t *) [with scalar_t=c10::Half]"
(659): here

E:\nvidia\torch-ngp\raymarching\src\raymarching.cu(777): warning #177-D: variable "near" was declared but never referenced
          detected during instantiation of "void kernel_march_rays(uint32_t, uint32_t, const int *, const scalar_t *, const scalar_t *, const scalar_t *, float, float, uint32_t, uint32_t, const scalar_t *, float, const scalar_t *, const scalar_t *, scalar_t *, scalar_t *, scalar_t *, uint32_t) [with scalar_t=double]"
(853): here

E:\nvidia\torch-ngp\raymarching\src\raymarching.cu(777): warning #177-D: variable "near" was declared but never referenced
          detected during instantiation of "void kernel_march_rays(uint32_t, uint32_t, const int *, const scalar_t *, const scalar_t *, const scalar_t *, float, float, uint32_t, uint32_t, const scalar_t *, float, const scalar_t *, const scalar_t *, scalar_t *, scalar_t *, scalar_t *, uint32_t) [with scalar_t=float]"
(853): here

2 errors detected in the compilation of "E:/nvidia/torch-ngp/raymarching/src/raymarching.cu".
raymarching.cu
ninja: build stopped: subcommand failed.

**Comment by ashawkey** [comment]
@francescofugazzi Please check https://github.com/ashawkey/torch-ngp/issues/47#issuecomment-1097627927, and give more details about your environment.

**Comment by francescofugazzi** [comment]
thanks for your reply
I changed the c++ to 17 in ll backend.py files but it's unclear to me how to set the vstool downgrade suggestion.
About my enviroment:
Windows 11
VS Studio 2022 Community updated to latest version
Cuda 11.6
Anaconda prompt

Previously I managed to install instant-ngp and nvdifferc without any particular problem... well about the latter it couldn't find Visual Studio path and I olved it by changing it removing (x86) in the paths and the same I did here with all backend.py files

**Comment by ashawkey** [comment]
So there is still problem after changing to `/std=c++17` (which solved the problem in that issue)?
Also, could you install the pytorch bindings of `tiny-cuda-nn`?

**Comment by francescofugazzi** [comment]
i confirm that i had no problems with tiny-cuda-nn, i only had to change the visual studio paths

**Comment by ashawkey** [comment]
@francescofugazzi I found [this](https://github.com/facebookresearch/pytorch3d/issues/1127#issuecomment-1071206320) related issue, could you try to remove all the `#include <torch/extension.h>` (like [this](https://github.com/ashawkey/torch-ngp/blob/main/raymarching/src/raymarching.cu#L7)) and build again? If that also fails, I would recommend downgrade CUDA...

**Comment by ashawkey** [comment]
I have pushed the mentioned changes in the latest commit, you can directly use this to try.

**Comment by francescofugazzi** [comment]
I tried but still nothing, I think it counts an error more now

File "C:\Users\franz\anaconda3\envs\torchngp\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\nvidia\torch-ngp\main_nerf.py", line 63, in <module>
    from nerf.network import NeRFNetwork
  File "E:\nvidia\torch-ngp\nerf\network.py", line 7, in <module>
    from .renderer import NeRFRenderer
  File "E:\nvidia\torch-ngp\nerf\renderer.py", line 9, in <module>
    import raymarching
  File "E:\nvidia\torch-ngp\raymarching\__init__.py", line 1, in <module>
    from .raymarching import *
  File "E:\nvidia\torch-ngp\raymarching\raymarching.py", line 9, in <module>
    from .backend import _backend
  File "E:\nvidia\torch-ngp\raymarching\backend.py", line 31, in <module>
    _backend = load(name='_raymarching',
  File "C:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\utils\cpp_extension.py", line 1144, in load
    return _jit_compile(
  File "C:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\utils\cpp_extension.py", line 1357, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\utils\cpp_extension.py", line 1469, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "C:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\utils\cpp_extension.py", line 1756, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension '_raymarching': [1/3] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc --generate-dependencies-with-compile --dependency-output raymarching.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=_raymarching -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include -IC:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include\TH -IC:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include" -IC:\Users\franz\anaconda3\envs\torchngp\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -c E:\nvidia\torch-ngp\raymarching\src\raymarching.cu -o raymarching.cuda.o
FAILED: raymarching.cuda.o
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc --generate-dependencies-with-compile --dependency-output raymarching.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=_raymarching -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include -IC:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include\TH -IC:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include" -IC:\Users\franz\anaconda3\envs\torchngp\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -c E:\nvidia\torch-ngp\raymarching\src\raymarching.cu -o raymarching.cuda.o
cl : warning della riga di comando D9025 : override di '/D__CUDA_NO_HALF_OPERATORS__' con '/U__CUDA_NO_HALF_OPERATORS__'
cl : warning della riga di comando D9025 : override di '/D__CUDA_NO_HALF_CONVERSIONS__' con '/U__CUDA_NO_HALF_CONVERSIONS__'
cl : warning della riga di comando D9025 : override di '/D__CUDA_NO_HALF2_OPERATORS__' con '/U__CUDA_NO_HALF2_OPERATORS__'
raymarching.cu
C:/Users/franz/anaconda3/envs/torchngp/lib/site-packages/torch/include\c10/macros/Macros.h(142): warning C4067: token imprevisti dopo una direttiva per il preprocessore. Previsto un carattere di nuova riga
cl : warning della riga di comando D9025 : override di '/D__CUDA_NO_HALF_OPERATORS__' con '/U__CUDA_NO_HALF_OPERATORS__'
cl : warning della riga di comando D9025 : override di '/D__CUDA_NO_HALF_CONVERSIONS__' con '/U__CUDA_NO_HALF_CONVERSIONS__'
cl : warning della riga di comando D9025 : override di '/D__CUDA_NO_HALF2_OPERATORS__' con '/U__CUDA_NO_HALF2_OPERATORS__'
raymarching.cu
C:/Users/franz/anaconda3/envs/torchngp/lib/site-packages/torch/include\c10/macros/Macros.h(142): warning C4067: token imprevisti dopo una direttiva per il preprocessore. Previsto un carattere di nuova riga
C:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include\pybind11\cast.h(1429): error: too few arguments for template template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
(1507): here

C:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include\pybind11\cast.h(1503): error: too few arguments for template template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
(1507): here

E:\nvidia\torch-ngp\raymarching\src\raymarching.cu(582): warning #177-D: variable "near" was declared but never referenced
          detected during instantiation of "void kernel_march_rays(uint32_t, uint32_t, const int *, const scalar_t *, const scalar_t *, const scalar_t *, float, float, uint32_t, uint32_t, const scalar_t *, float, const scalar_t *, const scalar_t *, scalar_t *, scalar_t *, scalar_t *, uint32_t) [with scalar_t=double]"
(658): here

E:\nvidia\torch-ngp\raymarching\src\raymarching.cu(582): warning #177-D: variable "near" was declared but never referenced
          detected during instantiation of "void kernel_march_rays(uint32_t, uint32_t, const int *, const scalar_t *, const scalar_t *, const scalar_t *, float, float, uint32_t, uint32_t, const scalar_t *, float, const scalar_t *, const scalar_t *, scalar_t *, scalar_t *, scalar_t *, uint32_t) [with scalar_t=float]"
(658): here

2 errors detected in the compilation of "E:/nvidia/torch-ngp/raymarching/src/raymarching.cu".
raymarching.cu
[2/3] cl /showIncludes -DTORCH_EXTENSION_NAME=_raymarching -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include -IC:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include\TH -IC:\Users\franz\anaconda3\envs\torchngp\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include" -IC:\Users\franz\anaconda3\envs\torchngp\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc /O2 /std:c++14 -c E:\nvidia\torch-ngp\raymarching\src\bindings.cpp /Fobindings.o

**Comment by neilgogogo** [comment]
hi, I met this and after downgraded cuda to 11.2 and changing std to C++ 17, it works

**Comment by ashawkey** [comment]
@neilgogogo Thanks for the information! I doubt it is caused by pybind's compatibility with CUDA 11.6, and currently the solution is to downgrade CUDA. (also check [this](https://discuss.pytorch.org/t/cuda-11-6-extension-problem/145830)).

**Comment by francescofugazzi** [comment]
thanks for all the tips :)
I downgraded cuda to 11:3 and deleted the environment and restarted from scratch... now i'm unbale to compile tiny-cuda :(
so i'm stopping even before

**Comment by francescofugazzi** [comment]
I managed to compile it :)
In every setup.py i changed the nvcc flag '-std=c++14' to '-std=c++17'
And I also added '-allow-unsupported-compiler'
In this way Cuda 11.3 can be used with Visual Studio 2022. I wans't able at all with Visual Studio 2019 as It kept on giving me problems whatever combination I tried.
I compiled every module separately and installed them as in your guide, because by launching the main script i was still getting problems. Now everything seems to work

**Comment by ashawkey** [comment]
Glad to hear that, thanks for the information!

**Comment by pfirmino** [comment]
Thanks @francescofugazzi, It compiled beutifully here lol

**Comment by letian-zhang** [comment]
@francescofugazzi That is really helpful for me. Thank you.
