### ISSUE TITLE
Can this reproduce the results of instant-ngp? What parameter should I use?

### ISSUE THREAD

**Issue by GaiZhenbiao** [ashawkey/torch-ngp#54]
I tried to reproduce NeRF results of instant-ngp with this repo, but I the PSNR I got is quite a bit lower than the original one. So what should I do to reproduce the results? Can this repo reproduce the results in the original paper?

**Comment by ashawkey** [comment]
Unfortunately, there is still a performancee gap (e.g., 33 compared to 35 for Lego).

**Comment by knelk** [comment]
@GaiZhenbiao which flags are you using for training?

@ashawkey do you have a feeling where the problem might be coming from?

**Comment by ashawkey** [comment]
There are lots of details and tricks in instant-ngp unimplemented here, I doubt about the density grid updation most now. You can check those TODOs (e.g., https://github.com/ashawkey/torch-ngp/blob/main/nerf/renderer.py#L415) if you are interested.

**Comment by ashawkey** [comment]
closed for now, any improvement will be noted in readme.
