### ISSUE TITLE
CLIP

### ISSUE THREAD

**Issue by ashmrz** [ashawkey/torch-ngp#57]
Hi. I've tried to run CLIP training with tcnn and it seems to be failing. Can you please explain the flags that you use for CLIP-informed training? 

Thank you very much.

**Comment by ashawkey** [comment]
Hi, the CLIP part is experimental and unfinished. I planned to try some [CLIP-NeRF](https://github.com/cassiePython/CLIPNeRF) like text-guided editing or [dreamfield](https://github.com/google-research/google-research/tree/master/dreamfields) like generative task, as an example of using this repo to perform downstream tasks.
I recommend not to try it now, but you can check this [script](https://github.com/ashawkey/torch-ngp/blob/main/scripts/run_gui_nerf_clip.sh) for an example of training a Lego and then edit its color to red.
