### ISSUE TITLE
Tips on how to tune "bound" & "scale" for a new scene?

### ISSUE THREAD

**Issue by JasonLSC** [ashawkey/torch-ngp#59]
I have a CG-generated dataset containing correct poses and depth range, exactly like Blender dataset. I used it to train a NeRF sucessfully by NeRF-pytorch code, but I failed to use it to train a NeRF by torch-ngp.

 I think it may be due to my wrong setting of "bound" & "scale" for this scene. So do you have any tips on how to tune "bound" & "scale" for a new scene?

**Comment by ashawkey** [comment]
@JasonLSC Hi, you can try to uncomment [this line](https://github.com/ashawkey/torch-ngp/blob/main/nerf/provider.py#L219) to check the poses. A proper dataset should have poses like in [this](https://github.com/ashawkey/torch-ngp/issues/47#issuecomment-1098657588). You can also check `colmap2nerf.py` to find the code to properly transform the poses.

**Comment by JasonLSC** [comment]
@ashawkey Hi, thank you for your instructions. The visualization of the poses looks like this:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/50308488/165673939-622d0a8e-f843-42c5-a2b6-2ef8e1dee005.png">
I think it's good?

**Comment by JasonLSC** [comment]
The depth range for each camera is [1.5m, 25m]. The radius of camera rig is about 5m.
The GUI visualization looks like this: (bound = 1, scale = 0.33)
![image](https://user-images.githubusercontent.com/50308488/165677441-0b9f215d-b22d-4033-88b6-1a56ab1e47c3.png)

**Comment by ashawkey** [comment]
Yes, the camera looks good. From the GUI it seems it is able to train normally? If you want the ray to reach further, you can use a larger bound.

**Comment by JasonLSC** [comment]
Hi @ashawkey ,thank you for your above sugguestions. Now, I can train my own scene dataset on the torch-NGP platform normally. In the end of training, the PSNR of training views converges to 26dB (bound = 8, scale = 1) . But, it converges to 30dB when I use NVIDIA intstant-NGP testbed (aabb_scale = 8, scale = 1)

I have some questions about torch_NGP and instant_NGP:

- Is 'bound' & 'scale' in your implementation correspond to 'aabb_scale ' & 'scale ' in instant-NGP?
- Do you have any idea about how to save rendered training view in the instatnt-NGP testbed?
- Why the desired resolution is correspond to the bound in torch-NGP nerf application? Is it same with the instant-NGP impelmentation?

**Comment by ashawkey** [comment]
There is still a large performance gap compared to the original implementation, it may still take some time for further optimization.
1. Yes, they are designed to function similarly, but there are differences as stated in readme.
2. I'm not sure about this, you could ask in their repo.
3. If you mean that we scale desired resolution with bound, yes, it is discussed in https://github.com/ashawkey/torch-ngp/issues/23.

**Comment by ashawkey** [comment]
closed for now.
