### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by Speido** [ashawkey/torch-ngp#6]
During JIT compilation I get:

ptxas fatal   : Unresolved extern function '_Z3powdi'
shencoder.cu
ninja: build stopped: subcommand failed.

Setup:
Windows 11, 21H2
pytorch: 1.10.2+cu102
nvcc: 10.2.89
GPU: 2080Ti
VS2019

Thank you.

**Comment by ashawkey** [comment]
The error seems similar to [this](https://stackoverflow.com/questions/31006581/cuda-device-unresolved-extern-function), and [this](https://forums.developer.nvidia.com/t/how-to-deal-with-ptxas-fatal-error-unresolved-extern-function-cudagetparameterbuffer/27441/3) is a solution on VS. 
Hope these can be helpful.

**Comment by Yannnnnnnnnnnn** [comment]
I fixed this error following this article:https://blog.csdn.net/rdw1246010462/article/details/120256966.

Origin Code:
```
# shencoder.cu L304
pow(z,3)
```

Changed Code:
```
# shencoder.cu L304
z*z*z
```
