### ISSUE TITLE
question about detach() in tensoRF

### ISSUE THREAD

**Issue by neilgogogo** [ashawkey/torch-ngp#60]
hi, I have a question about the detach(), I plan to add another network to optimise the positions of input points before throwing into the sigma and color features, but I find the variables will not optimize after the backpropagation and step. And after I look over the code, I find there is detach() function in the code. Do you think this is the reason bebind this?

![image](https://user-images.githubusercontent.com/53148705/165657286-d8c46d1e-3aeb-42b6-8fa9-afbfb27d76ad.png)

Many  thanks,

Neil

**Comment by ashawkey** [comment]
Yes, I followed the original implementation [here](https://github.com/apchenstu/TensoRF/blob/main/models/tensoRF.py#L26). You can try to remove that detach, but I am not sure what will happen.

**Comment by neilgogogo** [comment]
thank you very much foy your advice, i will try
