### ISSUE TITLE
bias=False

### ISSUE THREAD

**Issue by aoliao12138** [ashawkey/torch-ngp#61]
Hi, thank you for the great work!
I find the bias is set to False in the linear layer in network.py. I think maybe setting bias to be True will get a better result without losing speed? Am I wrong? Welcome discussing! Thank you very much!

**Comment by ashawkey** [comment]
@aoliao12138 Hi, it is intended to be similar to tiny-cuda-nn's fully fused MLP, which doesn't use bias. Of course you can try to enable it!

**Comment by ashawkey** [comment]
closed for now.
