### ISSUE TITLE
"Near distance" equivalent

### ISSUE THREAD

**Issue by cpacker** [ashawkey/torch-ngp#62]
Awesome repo!

Quick question - is there an equivalent setting for the "Near distance" GUI option in instant-ngp (https://github.com/NVlabs/instant-ngp/blob/ea65ab84b628b9b69838aa43a19cc060e71e4819/scripts/run.py#L40)?

I tried setting https://github.com/ashawkey/torch-ngp/blob/main/raymarching/src/raymarching.cu#L23 to `0.0` and recompiling, but it didn't seem to work (I get the same artifacts that appear when using the default `--near_distance` in instant-ngp, which are resolved using `--near_distance 0`).

**Comment by ashawkey** [comment]
@cpacker Hi, it is controlled by the `min_near` [here](https://github.com/ashawkey/torch-ngp/blob/main/raymarching/raymarching.py#L22), and you can expose in in `renderer.py`, such as [here](https://github.com/ashawkey/torch-ngp/blob/main/nerf/renderer.py#L131).  
The constant in the CUDA file is obsoleted and I forgot to remove it. I will add an option later!

**Comment by cpacker** [comment]
That worked great, thanks for the quick reply!
