### ISSUE TITLE
Noisy images (parameter advice?)

### ISSUE THREAD

**Issue by sergiobdrl** [ashawkey/torch-ngp#63]
I consistently get a very characteristic noise on top of my rendered rgbs. Any advice on how to make them better?

![image](https://user-images.githubusercontent.com/83932689/167912806-e943155d-d073-4959-9ff9-39465940ee9c.png)

**Comment by ashawkey** [comment]
@sergiobdrl I assume you are using the GUI mode? You could try the CMD mode, which usually saves images of better quality.

**Comment by sergiobdrl** [comment]
Thank you @ashawkey, I'm actually using the command line!

**Comment by ashawkey** [comment]
Maybe you could try to use a smaller scale and set `bound = 1` to disable adaptive ray marching, which accelerate the rendering in sacrifice of some rendering quality. But I'm not sure about how much it can help.
You can also try with instant-ngp first to see if it can remove such noise.

**Comment by ashawkey** [comment]
closed for now.
