### ISSUE TITLE
Error when using custom dataset (error output attached)?

### ISSUE THREAD

**Issue by tym0027** [ashawkey/torch-ngp#64]
Hello,

I am trying to use the custom dataset option for nerfs. I have successfully installed the software. I am training models using the synthetic lego nerf dataset.

However, I get an error when I try and use the custom dataset option. I successfully installed the colmap python libraries. When I run the code I get the following error sequence:

![image](https://user-images.githubusercontent.com/13397866/167915925-87a49a38-c3b4-46b8-bed3-36248c637b91.png)

Any help would be appreciated! Thanks!

**Comment by ashawkey** [comment]
@tym0027 Hi, I haven't tested with the python libraries of colmap, but this seems to be a problem of colmap. You could verify its installation first, e.g., by running their examples.

**Comment by cnzero** [comment]
> 

hi, @tym0027 I have the same problem, did you solve it? any solution and tips?
