### ISSUE TITLE
depth calculation

### ISSUE THREAD

**Issue by ShengyuH** [ashawkey/torch-ngp#67]
hi, 

Thanks for this effort. I have one question regarding depth calculation:
https://github.com/ashawkey/torch-ngp/blob/a66596089e8e14f9b3043c1d1b346e22a0bd7cf4/nerf/renderer.py#L227

Why it's 
```
depth = torch.sum(weights * ori_z_vals, dim=-1)
```

Instead of: 
```
depth = torch.sum(weights * z_vals, dim=-1)
```

I don't see the point of scaling the z_vals.

**Comment by ashawkey** [comment]
@ShengyuH Hi, it is just for convenience of saving depth as an image (so we need to scale it to `[0, 1]`). If you need the real depth value, you can modify the line the save another format.

**Comment by ShengyuH** [comment]
@ashawkey Thanks for your quick reply. Now it's clear to me.
