### ISSUE TITLE
Does this operator support second order differentiation? (hashgrid)

### ISSUE THREAD

**Issue by Dengzhi-USTC** [ashawkey/torch-ngp#7]
Hi, excellent work;
I try use it in our program, and find it can not support second order differentiation;
Do you implement it?
Thank you very much;

**Comment by ashawkey** [comment]
No, it doesn't support higher order derivitives for now. I think the original implementation doesn't have a use case for this?

**Comment by Dengzhi-USTC** [comment]
Yes, i also don't find this in the original implenmentation.
Thank you very much.
Do you have any plans to develop optimizations for higher order derivatives?

**Comment by ashawkey** [comment]
As the aim of this repo is to reproduce instant-ngp (and is unfinished yet), I don't have a plan to develop new functionality. Anyway, contributions are welcome.

**Comment by Dengzhi-USTC** [comment]
Ok，thank you very much.
