### ISSUE TITLE
Any plan for research intern recently ?

### ISSUE THREAD

**Issue by daili0015** [ashawkey/torch-ngp#74]
Sorry to use issue  to contact you. Cause I failed to find your email.
Do you have a plan to be a research intern? We are working on same thing really cool about nerf.
If you or your college classmates are interested, please let me know how to contact you.
My Email:  zhengchengyao@sensetime.com
Wechat:    zcy0017

**Comment by ashawkey** [comment]
Thanks for your invitation! I'll contact you via wechat later!
