### ISSUE TITLE
What does test speed mean?

### ISSUE THREAD

**Issue by himmetozcan** [ashawkey/torch-ngp#75]
Hi there. Thank you for this great implementation. I have a very simple question. What does test speed mean in [here](https://github.com/ashawkey/torch-ngp#performance-reference)? Is it like testing new pictures for the same object, after you finished training the model on the object with another set of pictures? What happens to test speed if I change the object in the testing phase, for ex. changing the color of it, but same shape?

**Comment by ashawkey** [comment]
@himmetozcan Hi, yes, the testing refers to performing novel view synthesis on the object trained from observed views (please refer to the NeRF paper for details). I don't thiink we can change the color or shape of a pretrined neural radiance field simply, but the speed usually depends on the complexity of the object (how much we can prune the ray sampling).

**Comment by GurcanDurukan** [comment]
Just to make it clear I have a question about NeRF implementation in this repository as well . Let us assume that we have two image datasets A and B both of which belongs to the same object.  We also know camera parameters, poses and transform matrices.. etc for both datasets. Images for both datasets may or may not have taken using the same camera. My question is if we train the algorithm using dataset A; do we have to use dataset A for testing purposes as well? Is it possible to train algorithm using dataset A then by using the weight obtained from dataset A making novel-view synthesis using dataset B and weights from dataset A?

**Comment by ashawkey** [comment]
Current implementation assumes the camera intrinsic is the same for all images, but this can be modified to use different camera intrinsic. Another problem is that we estimate the object center and scale (check colmap2nerf.py) based on all training poses and transform the poses to make the object fall in the bounding box. We need to apply the same transformation as A if we want to test on B.
So in theory it is possible to train on A and test on B, but in practice it needs some more efforts.
