### ISSUE TITLE
Training randomly broke with RuntimeError on Backpropagation

### ISSUE THREAD

**Issue by chenusc11** [ashawkey/torch-ngp#76]
Just wondering, has anyone encountered this problem before?

I tried to test the torch-ngp's network_tcnn in my own code. However, it sometimes randomly stopped by a weird error "RuntimeError: Function '_module_functionBackward' returned nan values in its 0th output. " This is really hard to debug since it occurs randomly.

Is this an amp error? or a tiny-cuda-nn error? It never happens if I didn't use AMP and tiny-cuda-nn. 

Update: last time I checked, this never happen if I don't use amp mixed precision. 

I pasted the log below:

/root/miniconda3/envs/torch-ngp/lib/python3.8/site-packages/toorch/autograd/__init__.py:173: UserWarning: Error detected in _module_functionBackward. Traceback of forward call that caused the error:
  File "run_nerf.py", line 333, in <module>
    train()
  File "run_nerf.py", line 324, in train
    train_nerf(args, train_dl, val_dl, hwf, i_split, near, far, render_poses)
  File "run_nerf.py", line 175, in train_nerf
    loss, psnr = train_nerf_on_epoch(args, train_dl, H, W, focal, N_rand, optimizer, loss_func, global_step, render_kwargs_train, scaler)
  File "run_nerf.py", line 55, in train_nerf_on_epoch
    rgb, disp, acc, extras = render(H, W, focal, chunk=args.chunk, rays=batch_rays, retraw=True, img_idx=img_idx, **render_kwargs_train)
  File "/home/shuaic/storage/nerf-pytorch-dev/script/models/rendering.py", line 261, in render
    all_ret = batchify_rays(rays, chunk, **kwargs)
  File "/home/shuaic/storage/nerf-pytorch-dev/script/models/rendering.py", line 206, in batchify_rays
    ret = render_rays(rays_flat[i:i+chunk], **kwargs)
  File "/home/shuaic/storage/nerf-pytorch-dev/script/models/rendering.py", line 154, in render_rays
    raw = network_query_fn(pts, viewdirs, img_idxs, network_fine, 'fine', output_transient, test_time=test_time)
  File "/home/shuaic/storage/nerf-pytorch-dev/script/models/nerfh_tcnn.py", line 288, in <lambda>
    run_NeRFH_TCNN(inputs, viewdirs, ts, network_fn, typ=typ,
  File "/home/shuaic/storage/nerf-pytorch-dev/script/models/nerfh_tcnn.py", line 413, in run_NeRFH_TCNN
    out_chunks += [fn(inputs_flat[i: i+netchunk], input_dirs_flat[i:i+netchunk], ts=ts[i:i+netchunk], output_transient=output_transient)]
  File "/root/miniconda3/envs/torch-ngp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/shuaic/storage/nerf-pytorch-dev/script/models/nerfh_tcnn.py", line 250, in forward
    density_outputs = self.density(x) # [65536, 3]
  File "/home/shuaic/storage/nerf-pytorch-dev/script/models/nerfh_tcnn.py", line 162, in density
    h = self.sigma_net(x)
  File "/root/miniconda3/envs/torch-ngp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/torch-ngp/lib/python3.8/site-packages/tinycudann/modules.py", line 119, in forward
    output = _module_function.apply(
 (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755903507/work/torch/csrc/autograd/python_anomaly_mode.cpp:104.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
 83%|█████████████████████████████████████████████████████████████████████████████▉                | 8288/10001 [8:05:58<1:40:26,  3.52s/it]
Traceback (most recent call last):
  File "run_nerf.py", line 333, in <module>
    train()
  File "run_nerf.py", line 324, in train
    train_nerf(args, train_dl, val_dl, hwf, i_split, near, far, render_poses)
  File "run_nerf.py", line 175, in train_nerf
    loss, psnr = train_nerf_on_epoch(args, train_dl, H, W, focal, N_rand, optimizer, loss_func, global_step, render_kwargs_train, scaler)
  File "run_nerf.py", line 75, in train_nerf_on_epoch
    scaler.scale(loss).backward()
  File "/root/miniconda3/envs/torch-ngp/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/miniconda3/envs/torch-ngp/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function '_module_functionBackward' returned nan values in its 0th output.

**Comment by ashawkey** [comment]
@chenusc11 Hi, thanks for the information. It seems you are using detect anomaly mode of pytorch? Have you tried to turn it off and see if the results are normal?

**Comment by chenusc11** [comment]
@ashawkey Thanks for the reply. No I didn't set detect anomaly myself. It seems to be happening when using tcnn. WIth the exactly same architecture of PyTorch, I didn't have this issue before.

**Comment by ashawkey** [comment]
@chenusc11 Since it seems to be a problem of tiny-cuda-nn, maybe you could ask in its repository too.

**Comment by chenusc11** [comment]
Thanks for the suggestion. Will do.

**Comment by taylorlu** [comment]
@chenusc11 Have you solved the problem? I meet the same issue now.

**Comment by chenusc11** [comment]
> @chenusc11 Have you solved the problem? I meet the same issue now.

Hi, unfortunately I couldn't solve the problem.

**Comment by taylorlu** [comment]
Hi, @chenusc11 

I think I have solved the problem, the primary reason was the half precision used in **tcnn**. In fact, even the pure pytorch code will throw the same error when you enable `--fp16`, I have tested.
The solution is to modify `torch.cuda.amp.GradScaler` settings in amp, however there's more handy way, just change the `eps` value in `torch.optim.Adam` to a larger value say 1e-6 enough.
https://github.com/ashawkey/torch-ngp/blob/5a7222a5c7629dc3153e01be1f0834489245ee45/main_nerf.py#L124
Maybe I can pull a request. :smile: @ashawkey 
And also, @ashawkey , why you add a abs loss to `deform` in dnerf, I cannot find any hint in the original paper, perhaps just add a tanh function `x = x + torch.tanh(deform)/hparam` will be more reasonable if you don't want the deviation uncontrollable.
https://github.com/ashawkey/torch-ngp/blob/5a7222a5c7629dc3153e01be1f0834489245ee45/dnerf/network.py#L140

**Comment by ashawkey** [comment]
@taylorlu Thanks for the help!
1. the `eps = 1e-15` is from instant-ngp's paper and it works well for native pytorch MLP (which I recommend to use), I haven't tried whether it would affect the performance of `--tcnn`. It would be nice if you could help to check it, and pull requests are welcome!
2. It's a good idea! I observed some drifting points in training so I add a loss to regularize it. I'll do some experiments to try the `tanh` activation.

**Comment by chenusc11** [comment]
@taylorlu @ashawkey I have solved my issue by removing the torch AMP package. I talked to the tiny-cuda-nn's author on one occasion recently, and he said the AMP is not needed. 

I verify the issue by removing the AMP, and it seems the error doesn't occur anymore.

I will close the issue for now. If anyone is suffering from the issue again, please feel free to open for more discussion.
