### ISSUE TITLE
Ray termination condition in training

### ISSUE THREAD

**Issue by kwea123** [ashawkey/torch-ngp#77]
https://github.com/ashawkey/torch-ngp/blob/0ed3f281900f4ccbcec5a314f7b25c78df586404/raymarching/src/raymarching.cu#L549-L551

I think the condition is wrong, and maybe it's the reason it didn't work for TensoRF. You are checking the weight of the current sample point instead of the accumulated weight. Either checking `ws>=1-1e-4` or `T<=1e-4` should be correct. The condition in `kernel_composite_rays` is correct.
https://github.com/ashawkey/torch-ngp/blob/0ed3f281900f4ccbcec5a314f7b25c78df586404/raymarching/src/raymarching.cu#L884-L886

Another possible improvement:
https://github.com/ashawkey/torch-ngp/blob/0ed3f281900f4ccbcec5a314f7b25c78df586404/raymarching/src/raymarching.cu#L672
The gradient factor w.r.t. `grad_weights_sum` should be simply `1 - ws_final` by math calculation, your formula is also correct since `T+ws` is always `1` but maybe harder to understand. Finally, if you want to add support for gradient w.r.t. depth, I derived its formula: `deltas[0] * grad_depth[0] * (T*t - (final_d-d))` which is pretty much the same as rgbs.

Thanks for your code, I learnt a lot (cuda)!

**Comment by ashawkey** [comment]
Thanks a lot for spotting the bug! I have fixed them in https://github.com/ashawkey/torch-ngp/commit/aeaa996598109a748ef5c31631509446dd90c4b5. I'll try to add the support for depth supervision later.
I learned a lot from nerf_pl too and really appreciate your work!

**Comment by kwea123** [comment]
Thanks, close for now.
