### ISSUE TITLE
color_space performance

### ISSUE THREAD

**Issue by chensjtu** [ashawkey/torch-ngp#81]
I've noticed that color_space can be converted to linear. I wonder about the performance between the "srgb" and "linear". For example, in Lego or in Fern

**Comment by ashawkey** [comment]
@chensjtu Hi, I remember using linear color space leads to a slightly lower PSNR on lego, although the visual effect seems better. Since the original instant-ngp defaults to linear, we keep this option to try for different scenes.

**Comment by chensjtu** [comment]
Thanks! The performance is consistent with my assumption.
