### ISSUE TITLE
poor performance for "flower" scene in  LLFF dataset

### ISSUE THREAD

**Issue by Fangkang515** [ashawkey/torch-ngp#88]
Thanks for your great job. 
I tested on LLFF dataset and found that NGP performed well in most scenarios, but I couldn't get good results in the "flower" scenario. And some results like follows:

![image](https://user-images.githubusercontent.com/34268707/181176849-efea1fa4-99bb-4816-ad66-bf1238b8b5e9.png)

Do you have any opinions and suggestions?
The complete running command is as follows:
_python3 main_nerf.py  /data/nerf/torch-ngp/datasets/nerf_llff_data/flower --mode blender --iters 4000 --workspace ./log/flower  --bound 20 --lr 0.02 -O_

Thanks again.

**Comment by ashawkey** [comment]
@Fangkang515 Hi, have you solved the problem? In fact, the conversion script still fails to properly convert the `flower` scene's camera parameters, and you may need to manually adjust it by `--scale` and `--offset`

**Comment by zParquet** [comment]
I met the same problem. And "leaves" scene seems have the same problem. At last I have to deprecate these two scenes.
