### ISSUE TITLE
Render quality seems worse than instant-ngp for nerf synthetic data (lego)?

### ISSUE THREAD

**Issue by zhaofuq** [ashawkey/torch-ngp#9]
![individualImage](https://user-images.githubusercontent.com/28824540/154417699-d10de213-ecac-48b9-9fb0-09b709e595df.png)
Is there something that I mess up? Thank you.

**Comment by ashawkey** [comment]
Thanks for reporting the bug! It seems to be caused by the weight regularization on encoder, I have fixed this in https://github.com/ashawkey/torch-ngp/commit/17d992488baad4932995993d9279596845d4e587, it should train better now.
