### ISSUE TITLE
the "intrinsics.txt"  in  scene "TanksAndTemple/Ignatius" seems wrong

### ISSUE THREAD

**Issue by Fangkang515** [ashawkey/torch-ngp#93]
Thanks for your great job!
I train to run the torch-ngp in the scene "TanksAndTemple/Ignatius",  but I found the script  [tanks2nerf.py](https://github.com/ashawkey/torch-ngp/blob/main/scripts/tanks2nerf.py#L44) run failed.  And I checked the "intrinsics.txt" in the scene "TanksAndTemple/Ignatius", it is totally  different from the other scenes. 

> the intrinsics.txt in scene TanksAndTemple/Ignatius: (It is not a 4x4 matrix)
<img width="424" alt="image" src="https://user-images.githubusercontent.com/34268707/182520049-52c490b8-e59f-4fbe-bf22-afdebafdee0c.png">

> the intrinsics.txt in scene TanksAndTemple/truck:
<img width="192" alt="image" src="https://user-images.githubusercontent.com/34268707/182520138-2872035e-eccd-4e26-ba04-37b308153d22.png">

And I check the [Tensorf](https://github.com/apchenstu/TensoRF) and [CCNerf](https://github.com/ashawkey/CCNeRF) repos too, it also has this problem. So I guess something wrong for the "instrinsics.txt" in the scen "TanksAndTemple/Ignatius" .  Could you please check the original intrinsics about the scene? 

Thanks very much.

**Comment by ashawkey** [comment]
@Fangkang515 Yes, this maybe a mistake in the dataset release. You can rewrite the intrinsics for Ignatius manually:
```
1166.56 0.0 960.0 0.0 
0.0 1166.57 540.0 0.0 
0.0 0.0 1.0 0.0 
0.0 0.0 0.0 1.0
```
