### ISSUE TITLE
Wrong error output when attempting to run 1-dimensional GridEncoder

### ISSUE THREAD

**Issue by Xallt** [ashawkey/torch-ngp#96]
When creating a GridEncoder with `input_dim=1` it does not produce an error
But when you try to run that encoder, it raises an error with a message `RuntimeError: GridEncoding: C must be 1, 2, 4, or 8.`
If you look at the code in `gridencoder/src/gridencoder.cu`, `grid_encode_forward_cuda`:
```
template <typename scalar_t>
void grid_encode_forward_cuda(const scalar_t *inputs, const scalar_t *embeddings, const int *offsets, scalar_t *outputs, const uint32_t B, const uint32_t D, const uint32_t C, const uint32_t L, const float S, const uint32_t H, const bool calc_grad_inputs, scalar_t *dy_dx, const uint32_t gridtype) {
    switch (D) {
        case 2: kernel_grid_wrapper<scalar_t, 2>(inputs, embeddings, offsets, outputs, B, C, L, S, H, calc_grad_inputs, dy_dx, gridtype); break;
        case 3: kernel_grid_wrapper<scalar_t, 3>(inputs, embeddings, offsets, outputs, B, C, L, S, H, calc_grad_inputs, dy_dx, gridtype); break;
        default: throw std::runtime_error{"GridEncoding: C must be 1, 2, 4, or 8."};
    }
    
}
```
So the message that it produces doesn't have anything to do with the actual error
There should either be some kind of check in `GridEncoder.__init__` for the specified `input_dim`, or the message in this error should be something like "GridEncoding: D must be 2 or 3."

**Comment by ashawkey** [comment]
@Xallt Thanks! It's a bug and 1D should work as well. You can try with the latest commit!

**Comment by Xallt** [comment]
@ashawkey Wow, thank you, I did actually need the 1D encoder :)

**Comment by sai-karthikeya-vemuri** [comment]
Hey, this is a little awkward opening it after years, but I am still unable to run 1D Hash grids. How were you able to do it? 

It would be great if you could provide some pointers. I am basically getting the same error.
